name: Training and Testing

on: 
    workflow_dispatch:
        inputs:
            input_text:
                description: 'How many epochs'     
                required: true
                default: '5'

jobs:

  run:

    runs-on: [ubuntu-latest]

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        id: hello
        uses: ./
        with:
            epochs: "${{ github.event.inputs.input_text }}"

      - name: Test model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "steps.hello.outputs.net"  > cifar_net.pth
        run: |
          pip install pandas
          pip install numpy
          pip install torch
          pip install torchvision
          pip install GitPython

          python test.py
    
     - name: Archive artifacts      
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: cifar_net.pth
