name: Training and Testing

on: [push]

jobs:

  run:

    runs-on: [ubuntu-latest]

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install pandas
          pip install numpy
          pip install torch
          pip install torchvision
          pip install GitPython

          chmod +r ./Customers.csv
          chmod +x ./zadanie1.py
          chmod +x ./train.py
          chmod +x ./test.py

          python train.py

        - name: Test model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python test.py

          cat metrics.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
