name: 'Docker'
inputs:
  epochs:  # id of input
    description: 'How many epochs'
    required: true
    default: '5'
outputs:
  net: # id of output
    description: 'Net'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.epochs }}